//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrisonLabor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrisonLabor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:
        ///============== BETA VERSION ==============
        ///0.10.0
        ///- reworked news pop-up window
        ///- fixed construction job
        ///- new system for removing mod from save (new button in mod menu)
        ///- wardens no longer deliver food if prisoners can get it from another room
        ///- added alert when prisoners can escape
        ///- prisoners now will pick up weapons if treated bad
        ///- fixed food reservation throwing errors
        ///- added prisoner sucicides
        ///- added +5 bonus to mood while prisoner have free time
        ///- added +5 bonus to mood if p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NewsFeed&gt;
        ///  &lt;!-- How to insert news: --&gt;
        ///  &lt;!-- [subtitle] for subtitle --&gt;
        ///  &lt;!-- [img] ... [/img] for image (inside name of file) --&gt;
        ///  &lt;!-- [gap] for gap --&gt;
        ///  &lt;patches&gt;
        ///    &lt;!--&lt;patch version=&quot;0.10.0&quot;&gt;
        ///      &lt;title&gt;Prison Labor Beta v0.10.0&lt;/title&gt;
        ///      &lt;items&gt;
        ///        &lt;item&gt;prisoners will now work in cold only if &quot;work&quot; time is set&lt;/item&gt;
        ///        &lt;item&gt;prisoners will now seek safe temperature when not supervised&lt;/item&gt;
        ///        &lt;item&gt;prisoners will respect forbidden items, if &quot;inspired&quot;&lt;/it [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NewsFeed&gt;
        ///  &lt;!-- How to insert news: --&gt;
        ///  &lt;!-- [subtitle] for subtitle --&gt;
        ///  &lt;!-- [img] ... [/img] for image (inside name of file) --&gt;
        ///  &lt;!-- [gap] for gap --&gt;
        ///  &lt;patches&gt;
        ///    &lt;!--&lt;patch version=&quot;0.10.0&quot;&gt;
        ///      &lt;title&gt;Prison Labor Beta v0.10.0&lt;/title&gt;
        ///      &lt;items&gt;
        ///        &lt;item&gt;prisoners will now work in cold only if &quot;work&quot; time is set&lt;/item&gt;
        ///        &lt;item&gt;prisoners will now seek safe temperature when not supervised&lt;/item&gt;
        ///        &lt;item&gt;prisoners will respect forbidden items, if &quot;inspired&quot;&lt;/it [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialFeed {
            get {
                return ResourceManager.GetString("TutorialFeed", resourceCulture);
            }
        }
    }
}
