//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrisonLabor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrisonLabor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:
        ///1.0.3
        ///- updated Traditional Chinese translation, thanks to shiuanyue
        ///1.0.2
        ///- set minimum 500 points for suicide event
        ///1.0.1
        ///- lowered chance for suicide incident
        ///1.0.0
        ///- fixed tutorial window constantly showing
        ///- fixed news pop-up auto-showing on minor changes too (it auto-shows only on major changes)
        ///============== 1.0 Pre-patch ==============
        ///0.10.1
        ///- reworked news pop-up window
        ///- fixed construction job
        ///- new system for removing mod from save (new button in mod menu)
        ///- wardens no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NewsFeed&gt;
        ///  &lt;!-- How to insert news: --&gt;
        ///  &lt;!-- [subtitle] for subtitle --&gt;
        ///  &lt;!-- [img] ... [/img] for image (inside name of file) --&gt;
        ///  &lt;!-- [gap] for gap --&gt;
        ///  &lt;patches&gt;
        ///    &lt;patch version=&quot;1.0.3&quot; silent=&quot;true&quot;/&gt;
        ///    &lt;patch version=&quot;1.0.2&quot; silent=&quot;true&quot;/&gt;
        ///    &lt;patch version=&quot;1.0.1&quot; silent=&quot;true&quot;/&gt;
        ///    &lt;patch version=&quot;1.0.0&quot; silent=&quot;true&quot;/&gt;
        ///    &lt;patch version=&quot;0.10.1&quot; silent=&quot;false&quot;&gt;
        ///      &lt;title&gt;Prison Labor v0.10.1&lt;/title&gt;
        ///      &lt;items&gt;
        ///        &lt;item&gt;This patch contains a lot of changes, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TutorialFeed&gt;
        ///  &lt;!-- How to insert rich text: --&gt;
        ///  &lt;!-- [subtitle] for subtitle --&gt;
        ///  &lt;!-- [img] ... [/img] for image (inside name of file) --&gt;
        ///  &lt;!-- [gap] for gap --&gt;
        ///  &lt;tutorials&gt;
        ///    &lt;tutorial key=&quot;Introduction&quot;&gt;
        ///      &lt;items&gt;
        ///        &lt;item&gt;[title]Prison Labor Mod - Introduction&lt;/item&gt;
        ///        &lt;item&gt;Are you new to Prison Labor Mod? Don&apos;t worry, in this tutorial you will learn how to use this mod.&lt;/item&gt;
        ///        &lt;item&gt;The main goal of this mod is to make prisoners work, but managing prisoners [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialFeed {
            get {
                return ResourceManager.GetString("TutorialFeed", resourceCulture);
            }
        }
    }
}
